package com.amadeus.xu.lexer;

public enum TokenType {
    IDENTIFIER, VARIABLE, LEFT_PARENTHESIS, RIGHT_PARENTHESIS, LEFT_BRACES, RIGHT_BRACES, COMMA, RETURN, IF, BIGGER, BIGGER_EQUAL, ELSE, PLUS, MARK, MINUS, SEMICOLON, DOT, SLASH, BACKSLASH, ASTERISK, QUOTATION_MARK, FLOAT, INT, HASH, STRING, IMPORT, XU, TRUE, FALSE, WHILE, FOR, EQUAL, EQUAL_EQUAL, NOT_EQUAL, LESS, LESS_EQUAL, OR, AND, AUTO, CONST, OPENBRACKET, CLOSEBRACKET, EOF
}
