package com.amadeus.xu.lexer;

public enum TokenType {
    IDENTIFIER, VARIABLE, LEFT_PARENTHESIS, RIGHT_PARENTHESIS, LEFT_BRACES, RIGHT_BRACES, COMMA, RETURN, IF, BIGGER_THAN, ELSE, PLUS, MARK, MINUS, SEMICOLON, DOT, QUOTATION_MARK, FLOAT, INT, HASH, STRING, IMPORT, XU, TRUE, FALSE, WHILE, FOR, EOF
}
