package org.xu.scanner;

public enum TokenType {

    INT, FLOAT, PLUS, MINUS, STAR, IDENTIFIER, PUBLIC, LOCKED, EOF, MARK, SLASH,
    GREATER, GREATER_EQUAL, LESS, LESS_EQUAL, EQUAL_EQUAL, EQUAL, AND, BITWISE_AND, MARK_EQUAL,
    OR, BITWISE_OR, LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, IF, ELSE,
    TRUE, FALSE, STRING, PRINT, SEMICOLON, FOR, WHILE, CHAR
}
